In [2]:
import numpy as np
l1=[1,2,3,4]
np1=np.array(l1)
print(np1)
print(type(np1))


[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
np2=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np2)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(np1[2])

3


In [6]:
print(np1)

[1 2 3 4]


In [7]:
print(np2[1,2])
np2[1,2]=16

6


In [8]:
print(np2)

[[ 1  2  3]
 [ 4  5 16]
 [ 7  8  9]]


In [9]:
print(len(np1))
print(len(np2))

4
3


In [10]:
random1=np.ones((3,3),dtype='int')

In [11]:
print(random1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
random2=np.full((3,3)," ")
print(random2)

[[' ' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]


In [40]:
def check_win(board,user_value):
  for i in range(0,3):
    if(np.all(board[i]==user_value) or np.all(board[:i]==user_value)):
      return True
  if(np.all(np.diag(board)==user_value)):
    return True
  return False
def game_starts():
  board=np.full((3,3)," ")
  player1=input("Enter you name player 1")
  player2=input("Enter you name player 2")
  check=player1
  while True:
    if check==player1:
      print(player1,"It's your chocie")
    else:
      print(player2,"its your choice")
    print(board)
    row=int(input("enter row"))
    col=int(input("enter col"))
    if board[row][col]!=" ":
      print("it is already occupied")
      continue
    if check==player1:
      board[row][col]='x'
      if(check_win(board,'x')):
        print(board)
        print(player1,"won")
        break
    else:
      board[row][col]='o'
      if(check_win(board,'o')):
        print(board)
        print(player1,"won")
        break
    if check==palyer1:
      check=player2
    else:
      check=player1
print("tic tac toe")
play1=input("are you ready yes or no")
if(play1=="yes"):
  game_starts()
else:
  print("you choose not to play")







tic tac toe
are you ready yes or noyes
Enter you name player 1navya
Enter you name player 2rithin
navya It's your chocie
[[' ' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]
enter row1
enter col1
[[' ' ' ' ' ']
 [' ' 'x' ' ']
 [' ' ' ' ' ']]
navya won


In [ ]:
idmat=np.identity(3)
print(idmat)

In [41]:
num1=float(input("enter number"))
num2=float(input("enter number"))
np.add(num1,num2)

enter number10
enter number20


30.0

In [42]:
np1=np.array([1,2,3,4])
np.median(np1)

2.5

In [43]:
np2=np1
np3=np1.copy()

In [44]:
np3[2]=10
print(np3)
print(np1)

[ 1  2 10  4]
[1 2 3 4]


In [45]:
import time
import numpy as np
l1=[i for i in range(10**6)]
np3=np.array(l1)
time_list=time.time()
sum_total=sum(l1)
endtime_list=time.time()
sum2=0
time_numpy=time.time()
sum2=np.sum(np3)
endtime_numpy=time.time()
print("list",endtime_list-time_list)
print("numpy",endtime_numpy-time_numpy)

list 0.0068988800048828125
numpy 0.0013403892517089844
